- name: New AKS Cluster
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    shell: az group create -l {{AKS_location}} -n {{AKS_resource_group}}

  - name: Create an AKS cluster
    shell: az aks create --resource-group {{AKS_resource_group}} --name {{aks_name}} --kubernetes-version {{k8s_version}} --location {{AKS_location}} --node-vm-size Standard_D2_v3 --node-count {{node_count}} --generate-ssh-keys

  - name: Setting kubeconfig for the cluster
    shell: az aks get-credentials --resource-group {{ AKS_resource_group }} --name {{ aks_name }}
    register: result
  - debug: 
           var: result.stdout
  - name: setting context
    shell: kubectl config use-context {{ aks_name }} 
  
  - name: Creating namesapce
    k8s:
      name: ingress-nginx
      api_version: v1
      kind: Namespace
      state: present
 
  - name: Setting up nginx ingress controller
    shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml
  
  - name: Pause for 2 minutes for controller to become active
    pause:
      minutes: 2

  - name: Getting external IP from ingress
    shell: kubectl -n ingress-nginx get svc ingress-nginx-controller -o json | jq -r .status.loadBalancer.ingress[].ip
    register: external_ip

  - name: creating the spec.yaml file
    template:
        src: spec_tpl.j2
        dest: $HOME/spec_aks.yaml
  