- name: New AKS Cluster
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ AKS_resource_group }}"
      location: "{{ AKS_location }}"
  - name: Create an AKS cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ AKS_location }}"
      kubernetes_version: "{{ k8s_version }}"
      resource_group: "{{ AKS_resource_group }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: dyce_1
          count: 1
          vm_size: Standard_DS_v2
  - name: Setting kubeconfig for the cluster
    ansible.builtin.shell: az aks get-credentials --resource-group {{ AKS_resource_group }} --name {{ aks_name }}
    register: result
  - debug: 
           var: result.stdout_lines
  - name: setting context
    ansible.builtin.shell: kubectl config use-context {{ aks_name }} 
  
  - name: Creating namesapce
    ansible.builtin.shell: kubectl create namespace ingress-nginx 
 
  - name: Setting up nginx ingress controller
    ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml
  
  - name: Pause for 2 minutes for controller to become active
    pause:
      minutes: 2

  - name: Getting external IP from ingress
    ansible.builtin.shell: kubectl -n ingress-nginx get svc ingress-nginx-controller -o json | jq -r .status.loadBalancer.ingress[].hostname
    register: external_ip

  - name: creating the spec.yaml file
    template:
        src: spec_tpl.j2
        dest: $HOME/spec_aks.yaml
  